### ISSUE TITLE
Add Session Based Workflow

### ISSUE THREAD

**Issue by Techie09** [Techie09/readr#5]
### Description: ###
Session based Workflow should require an end-user to login with their account to begin a session, since some publications do not contain an ISBN, the ISBN would be recommended but not required. A description field would be required if the ISBN is not given. The description is information to help the end-user know what material is being read during the session. An example would be reading the New York Times on Sunday 1/26/2020. This would be information to cite in the description since an ISBN is not available. The user should be able to stop the session, and start a new session while logged in. 

### Tasks: ###
- [ ] Complete Auth Account Management #29 
- [ ] Manage Session Start Data #30 
- [ ] Add functionality to Stop a Session #31
